server:
  port: 8081
spring:
  application:
    name: "UsersProject"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
aws:
  accessKey: ${ACCESS_KEY}
  secretKey:  ${SECRET_KEY}
  region: ${REGION}
  cognito:
    userPoolId: ${USER_POOL_ID}
    clientId:  ${CLIENT_ID}
    region: ${REGION}
    clientSecret: ${CLIENT_SECRET}
  dynamodb:
    tableName: Users
    region: ${REGION}
adapter:
  cognito:
    secret: "<cognito-credentials-secret-name>"
    timeout: 5000
    endpoint: "https://<domain>.auth.<region>.amazoncognito.com/oauth2/token"
